name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Cache Ruby gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: gems-${{ hashFiles('Gemfile.lock') }}
          restore-keys: gems-

      - name: Install Ruby gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Setup TeX Live
        uses: paolobrasolin/setup-texlive-action@v1.0.2
        with:
          packages-path: ${{ github.workspace }}/.github/texlive.packages
          profile-path: ${{ github.workspace }}/.github/texlive.profile

      - name: Debug
        run: dvisvgm -V1

      - name: Cache anTeX artifacts
        uses: actions/cache@v2
        with:
          path: .antex-cache
          key: antex-cache-
          restore-keys: antex-cache-

      - name: Build
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        if: success()
        with:
          build_dir: _site
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
